server:
    port: 8084
spring:
    application:
        name: e_commerce
    datasource:
        password: Akola@123
        url: jdbc:mysql://localhost:3306/ECommerce?createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
