server:
    port: 8084
spring:
    application:
        name: e_commerce
    datasource:
        password:
        url: jdbc:mysql://localhost:3306/ECommerce?createDatabaseIfNotExist=true
        username:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
